resource_query:
  description: >
    Fully understand {user_prompt} and break down the prompt into a list of specific questions in order to answer user's questions.
    The list of questions will then be used by your colleague to find the resources from the resources pool.
    Leverage your reasoning skills, critical thinking, and problem solving skills
    Combine your questions with suggestions of the data_source (if using internal source) and/or query (if using external data sources) that might contain the relevant information for the next agent to find the relevant information within the directory.
    The internal directory includes:

    {files}
    Important:
    - Make sure the questions are specific to the user's prompt:
    
    {user_prompt}.
  expected_output: >
    A list of questions (as clear, simple as possbile, do not include summary) that can be used by the next agent to step by step find the more accurate information (either using internal sources or external sources) in order to answer the {user_prompt}.
    Important:
    - use bullet points for questions
    <sample>
    1. What is the total revenue of Company A in 2023? {relevant info: {internal_source: "Company_A_Financials_2023.pdf"}}
    2. What are the key market trends in the technology sector for 2024? {relevant info: {external_source_query: "latest technology market trends 2024"}}
    </sample>

resource_pulling:
  description: >
    tool_choice='required'
    Based on the <context> from the previous agents:
    - Answer all the questions from the first agent by pulling the most relevant information from the relevant documents.

    You are only allowed to pull information from the knowledge pool and exteral sources by performing web search and web scraping, and generating dummy data that are not exists in the documents or external sources are strictly prohibited.

    <important>
    - Relevant documents means those documents that marked as (relevant doc).
    - If the user’s query can be answered via one of the tool definitions, you must call the correct tool and specify its name and arguments. Don’t answer in plain text unless no tool applies.
    - DO NOT MAKE UP DATA / USE DUMMY DATA / HALLUCINATE.
    </important>
  expected_output: >
    Comprehensive report (with proper headings and formatting) that answer ALL questions from the first agent.
